/**
 * faber.agent
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.rootsid.wal.agent.api.model.didcomm

import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.rootsid.wal.library.didcomm.common.DidCommDataTypes
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*


@Schema
data class Message(
    @Schema(
        description = "Message identifier from previous message",
        example = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    )
    val pthid: String,

    @Schema(
        description = "Message as text",
        example = "{\"msg\": \"Hi Alice\"}"
    )
    val body: String,

    @Schema(
        description = "Sender's did",
        example = "did:peer:2.Ez6LSi2DUKWessWhBACa8UBKjLSuPjyni3fjMgfrpCVDcErcf.Vz6MkgUkVUpzJ8KEqJTfyoKR8Xfe...",
        pattern = "^did:peer:([\\d+]).*"
    )
    val from: String,

    @Schema(
        description = "Receiver's did",
        example = "did:peer:2.Ez6LSi2DUKWessWhBACa8UBKjLSuPjyni3fjMgfrpCVDcErcf.Vz6MkgUkVUpzJ8KEqJTfyoKR8Xfe...",
        pattern = "^did:peer:([\\d+]).*"
    )
    val to: String,

    @Schema(
        description = "Message identifier",
        example = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    )
    val id: String = UUID.randomUUID().toString(),

    @Schema(description = "Message type", example = "didcomm/v2")
    val type: String = DidCommDataTypes.ConnectionProtocol.DIDCOMM_2_0.value,
)

fun Message.toJson(): String = jacksonObjectMapper().writeValueAsString(this)


