/**
* faber.agent
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v0.7.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.rootsid.wal.agent.api.model.outofband

import io.swagger.v3.oas.annotations.media.Schema


/**
 * 
 * @param kid Key identifier, in W3C did:key or DID URL format
 */
@Schema
data class AttachDecoratorDataJWSHeader (
    @Schema(description = "Key identifier, in W3C did:key or DID URL format", example = "did:sov:LjgpST2rjsoxYegQDRm7EL#keys-4",
        pattern = "^did:(?:key:z[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+|sov:[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}(;.*)?(\\?.*)?#.+)\$")
    val kid: String
) {

}

