/**
 * faber.agent
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.rootsid.wal.agent.api.model.outofband

import io.swagger.v3.oas.annotations.media.Schema

/**
 *
 * @param header
 * @param &#x60;protected&#x60; protected JWS header
 * @param signature signature
 */
@Schema
data class AttachDecoratorData1JWS(
    val header: AttachDecoratorDataJWSHeader,

    @Schema(description = "Protected JWS header", example = "ey4uLn0", pattern = "^[-_a-zA-Z0-9]*\$")
    val `protected`: String? = null,

    @Schema(description = "Signature", example = "ey4uLn0", pattern = "^[-_a-zA-Z0-9]*\$")
    val signature: String,
) {

}

