/**
* faber.agent
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v0.7.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.rootsid.wal.agent.api.model.outofband


/**
 * 
 * @param kid Key identifier, in W3C did:key or DID URL format
 */
data class AttachDecoratorDataJWSHeader (
    /* Key identifier, in W3C did:key or DID URL format */
    val kid: String
) {

}

