/**
 * faber.agent
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.7.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.rootsid.wal.agent.api.model.outofband

import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import io.swagger.v3.oas.annotations.media.ArraySchema
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*


@Schema
data class InvitationMessage(
    @Schema(
        description = "Message identifier [id used for context as pthid]",
        example = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    )
    val id: String,

    @Schema(description = "Message type", example = "https://didcom.org/out-of-band/2.0/invitation")
    val type: String = "https://didcom.org/out-of-band/2.0/invitation",

    @Schema(
        description = "Sender's did",
        example = "did:peer:2.Ez6LSi2DUKWessWhBACa8UBKjLSuPjyni3fjMgfrpCVDcErcf.Vz6MkgUkVUpzJ8KEqJTfyoKR8Xfe...",
        pattern = "^did:peer:([\\d+]).*"
    )
    val from: String,

    @Schema(description = "Optional invitation body")
    val body: BodyDecorator? = null,

    @ArraySchema(arraySchema = Schema(description = "Optional invitation attachments"))
    val attachments: List<AttachDecorator>? = null,

    @Schema(description = "Optional label", example = "Bod")
    val label: String? = null
)

fun InvitationMessage.toBase64(): String = Base64.getEncoder().encodeToString(jacksonObjectMapper().writeValueAsString(this).toByteArray())

